apiVersion: v1
kind: Service
metadata:
  name: iron-defer
  labels:
    app: iron-defer
spec:
  type: ClusterIP
  selector:
    app: iron-defer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
