//! iron-defer application crate.
//!
//! Use-case orchestration and port traits. Depends only on the domain crate.
//! Per the architecture rule "no logic in lib.rs", this file only re-exports.

#![forbid(unsafe_code)]
// `async-trait` expands async trait methods into `Pin<Box<dyn Future>>`
// return types that are already `#[must_use]`. Clippy 1.99's
// `double_must_use` flags this macro-generated combination as redundant;
// the attribute is generated by the macro, so allow the lint crate-wide.
#![allow(clippy::double_must_use)]

pub mod config;
pub mod metrics;
pub mod observability;
pub mod ports;
pub mod registry;
pub mod services;

pub use crate::config::{
    AppConfig, DatabaseConfig, ObservabilityConfig, ProducerConfig, ServerConfig, WorkerConfig,
};
pub use crate::metrics::{
    CLAIM_BACKOFF_SECONDS, CLAIM_BACKOFF_TOTAL, IDEMPOTENCY_KEYS_CLEANED_TOTAL, Metrics,
    POOL_CONNECTIONS_ACTIVE, POOL_CONNECTIONS_IDLE, POOL_CONNECTIONS_TOTAL, SUSPEND_TIMEOUT_TOTAL,
    TASK_ATTEMPTS_TOTAL, TASK_DURATION_SECONDS, TASK_FAILURES_TOTAL, TASKS_PENDING, TASKS_RUNNING,
    TASKS_SUSPENDED_TOTAL, WORKER_POOL_UTILIZATION, ZOMBIE_RECOVERIES_TOTAL,
};
pub use crate::observability::StateTransitionEvent;
pub use crate::ports::{
    RecoveredTask, RecoveryOutcome, TaskExecutor, TaskRepository, TransactionalTaskRepository,
};
pub use crate::registry::{TaskHandler, TaskRegistry};
pub use crate::services::{SchedulerService, SweeperService, WorkerService, drain_join_set};
